version: 1.0
service_name: cwe-collector

stages:
    -
        name: PR Test
        when:
            - pull_request
            - pull_request:
                trigger_phrase: test it
        image: node:14
        compute_size: small
        commands:
            - npm install 
            - npm test
    -
        name: Integration Push - Coverage
        when:
            - push: ['integration']
        image: node:14
        compute_size: small
        commands:
            - make test
            - git clone git@algithub.pd.alertlogic.net:alertlogic/al-ps-tools.git
            - cp coverage/cobertura-coverage.xml cwe-collector.coverage.xml
            - bash ./al-ps-tools/helpers/collect.sh -c 'cwe-collector.coverage.xml'
            - rm -rf ./al-ps-tools/
            - echo done
        outputs:
            file: ./.ps_outputs/*     
