version: 1.0
service_name: cwe-collector

stages:
    -
        name: PR Test
        when:
            - pull_request
            - pull_request:
                trigger_phrase: test it
        image: node:18
        compute_size: small
        commands:
            - npm install 
            - npm test
    -
        name: When Tag Created Run Coverage
        when:
            - tag: ['v?\d+.\d+.\d+']
        image: node:18
        compute_size: small
        commands:
            - make test
            - git clone git@algithub.pd.alertlogic.net:alertlogic/al-ps-tools.git
            - cp coverage/cobertura-coverage.xml cwe-collector.coverage.xml
            - bash ./al-ps-tools/helpers/collect.sh -c 'cwe-collector.coverage.xml'
            - rm -rf ./al-ps-tools/
            - echo done
        outputs:
            file: ./.ps_outputs/*     
    -
        name: When Tag Created Run Build And Create Aritifacts
        when:
            - tag: ['v?\d+.\d+.\d+']
        image: 422372788747.dkr.ecr.us-east-1.amazonaws.com/al-paws-collector-pipeline:latest
        compute_size: small_arm
        commands:
           - source $NVM_DIR/nvm.sh && nvm use 18
           - npm install
           - make compile test package
           - mkdir cwe-collector
           - cp -r cfn al-cwe-collector.zip al-cwe-collector.json cwe-collector
           - zip -r cwe-collector.zip cwe-collector
        outputs:
           file: ./cwe-collector*
        packagers:
           - basic 